using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;

namespace DataAccess.Enums
{
    public enum OpenAIChatRole
    {
        //https://platform.openai.com/docs/guides/text-generation
        [Description("system")]
        System = -1, //The system role act as top-level instructions to the model, and typically
                     //describe what the model is, what it is supposed to do, and how it should
                     //generally behave and respond.

        [Description("assistant")]
        Assistant = 1, // The assistant role is presumed to have been generated by the model.

        [Description("user")]
        User = 2, // The user role is the requestors input.
        
    }
}
